---
- name: Install Apache on centos 7
  hosts: web
  vars:
    hostname: web1.tum.local
  tasks:
    - name: Install yum
      yum:
        name: httpd
        state: latest
    - name: Start Service
      service:
        name: httpd
        state: started
        enabled: true
    - name: Config Firewalld
      firewalld:
        service: http
        permanent: yes
        state: enabled
        immediate: yes
    - name: Create First Html File
      template:
        src: index.html.j2
        dest: /var/www/html/index.html
        owner: apache
        group: apache
        mode: '0644'
